// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';
import 'tag_api.dart';

// These functions are ignored because they are not marked as `pub`: `domain_item_to_ffi`, `ffi_item_to_domain`, `str_to_ct`

Future<Tag> createCollection({
  required String name,
  String? parentId,
  required String collectionType,
}) => RustLib.instance.api.crateApiCollectionApiCreateCollection(
  name: name,
  parentId: parentId,
  collectionType: collectionType,
);

Future<Tag?> getCollection({required String id}) =>
    RustLib.instance.api.crateApiCollectionApiGetCollection(id: id);

Future<List<Tag>> getCollections({String? filterType}) => RustLib.instance.api
    .crateApiCollectionApiGetCollections(filterType: filterType);

Future<List<TagItem>> getCollectionItems({required String collectionId}) =>
    RustLib.instance.api.crateApiCollectionApiGetCollectionItems(
      collectionId: collectionId,
    );

Future<TagItem> addItemToCollection({
  required String collectionId,
  required TagItemType itemType,
  required String targetId,
  required bool inheritLock,
}) => RustLib.instance.api.crateApiCollectionApiAddItemToCollection(
  collectionId: collectionId,
  itemType: itemType,
  targetId: targetId,
  inheritLock: inheritLock,
);

Future<void> removeItemFromCollection({
  required String collectionId,
  required String itemId,
}) => RustLib.instance.api.crateApiCollectionApiRemoveItemFromCollection(
  collectionId: collectionId,
  itemId: itemId,
);

Future<void> reorderCollectionItems({
  required String collectionId,
  required List<String> itemIds,
}) => RustLib.instance.api.crateApiCollectionApiReorderCollectionItems(
  collectionId: collectionId,
  itemIds: itemIds,
);

Future<void> setCollectionLock({
  required String collectionId,
  required bool isLocked,
}) => RustLib.instance.api.crateApiCollectionApiSetCollectionLock(
  collectionId: collectionId,
  isLocked: isLocked,
);

Future<void> startPlaying({
  required String collectionId,
  required int startIndex,
  required PlatformInt64 playbackPositionMs,
}) => RustLib.instance.api.crateApiCollectionApiStartPlaying(
  collectionId: collectionId,
  startIndex: startIndex,
  playbackPositionMs: playbackPositionMs,
);

Future<void> stopPlaying({required String collectionId}) => RustLib.instance.api
    .crateApiCollectionApiStopPlaying(collectionId: collectionId);

Future<void> updatePlaybackState({
  required String collectionId,
  required int currentIndex,
  required PlatformInt64 playbackPositionMs,
  required bool wasPlaying,
}) => RustLib.instance.api.crateApiCollectionApiUpdatePlaybackState(
  collectionId: collectionId,
  currentIndex: currentIndex,
  playbackPositionMs: playbackPositionMs,
  wasPlaying: wasPlaying,
);

Future<void> updateCollectionMetadata({
  required String collectionId,
  required TagMetadata metadata,
}) => RustLib.instance.api.crateApiCollectionApiUpdateCollectionMetadata(
  collectionId: collectionId,
  metadata: metadata,
);

Future<List<String>> resolveContent({
  required String collectionId,
  required BigInt maxDepth,
}) => RustLib.instance.api.crateApiCollectionApiResolveContent(
  collectionId: collectionId,
  maxDepth: maxDepth,
);

Future<bool> wouldCreateCircularReference({
  required String parentId,
  required String targetId,
}) => RustLib.instance.api.crateApiCollectionApiWouldCreateCircularReference(
  parentId: parentId,
  targetId: targetId,
);

/// Deep-copy all items from source collection into target, recursively.
/// Returns the number of song units copied.
Future<int> deepCopyCollection({
  required String sourceId,
  required String targetId,
  required BigInt maxDepth,
}) => RustLib.instance.api.crateApiCollectionApiDeepCopyCollection(
  sourceId: sourceId,
  targetId: targetId,
  maxDepth: maxDepth,
);

/// Remove duplicate song unit entries, keeping first occurrence. Returns removed count.
Future<int> deduplicateCollection({required String collectionId}) => RustLib
    .instance
    .api
    .crateApiCollectionApiDeduplicateCollection(collectionId: collectionId);

/// Shuffle a collection's items. Locked groups stay together as blocks.
/// If current_song_id is provided, that song is placed at index 0.
Future<void> shuffleCollection({
  required String collectionId,
  String? currentSongId,
}) => RustLib.instance.api.crateApiCollectionApiShuffleCollection(
  collectionId: collectionId,
  currentSongId: currentSongId,
);
