// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

// These functions are ignored because they are not marked as `pub`: `collection_type_to_string`, `item_type_to_string`, `string_to_collection_type`, `string_to_item_type`, `to_dart_collection_item`, `to_dart_collection`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`

Future<DartCollection> createCollection({
  required String name,
  String? parentId,
  required String collectionType,
}) => RustLib.instance.api.crateApiCollectionApiCreateCollection(
  name: name,
  parentId: parentId,
  collectionType: collectionType,
);

Future<DartCollection?> getCollection({required String id}) =>
    RustLib.instance.api.crateApiCollectionApiGetCollection(id: id);

Future<List<DartCollection>> getCollections({String? filterType}) => RustLib
    .instance
    .api
    .crateApiCollectionApiGetCollections(filterType: filterType);

Future<List<DartCollectionItem>> getCollectionItems({
  required String collectionId,
}) => RustLib.instance.api.crateApiCollectionApiGetCollectionItems(
  collectionId: collectionId,
);

Future<DartCollectionItem> addItemToCollection({
  required String collectionId,
  required String itemType,
  required String targetId,
  required bool inheritLock,
}) => RustLib.instance.api.crateApiCollectionApiAddItemToCollection(
  collectionId: collectionId,
  itemType: itemType,
  targetId: targetId,
  inheritLock: inheritLock,
);

Future<void> removeItemFromCollection({
  required String collectionId,
  required String itemId,
}) => RustLib.instance.api.crateApiCollectionApiRemoveItemFromCollection(
  collectionId: collectionId,
  itemId: itemId,
);

Future<void> reorderCollectionItems({
  required String collectionId,
  required List<String> itemIds,
}) => RustLib.instance.api.crateApiCollectionApiReorderCollectionItems(
  collectionId: collectionId,
  itemIds: itemIds,
);

Future<void> setCollectionLock({
  required String collectionId,
  required bool isLocked,
}) => RustLib.instance.api.crateApiCollectionApiSetCollectionLock(
  collectionId: collectionId,
  isLocked: isLocked,
);

Future<void> startPlaying({
  required String collectionId,
  required int startIndex,
  required PlatformInt64 playbackPositionMs,
}) => RustLib.instance.api.crateApiCollectionApiStartPlaying(
  collectionId: collectionId,
  startIndex: startIndex,
  playbackPositionMs: playbackPositionMs,
);

Future<void> stopPlaying({required String collectionId}) => RustLib.instance.api
    .crateApiCollectionApiStopPlaying(collectionId: collectionId);

Future<void> updatePlaybackState({
  required String collectionId,
  required int currentIndex,
  required PlatformInt64 playbackPositionMs,
  required bool wasPlaying,
}) => RustLib.instance.api.crateApiCollectionApiUpdatePlaybackState(
  collectionId: collectionId,
  currentIndex: currentIndex,
  playbackPositionMs: playbackPositionMs,
  wasPlaying: wasPlaying,
);

/// Update the full collection metadata (items, playback state, flags).
///
/// This is the "bulk update" path used by the Dart `_updateActiveQueue()`
/// method so that all metadata fields are persisted in a single write.
Future<void> updateCollectionMetadata({
  required String collectionId,
  required List<DartCollectionItem> items,
  required int currentIndex,
  required PlatformInt64 playbackPositionMs,
  required bool wasPlaying,
  required bool removeAfterPlay,
  required bool isLocked,
  required int displayOrder,
  required bool isQueue,
}) => RustLib.instance.api.crateApiCollectionApiUpdateCollectionMetadata(
  collectionId: collectionId,
  items: items,
  currentIndex: currentIndex,
  playbackPositionMs: playbackPositionMs,
  wasPlaying: wasPlaying,
  removeAfterPlay: removeAfterPlay,
  isLocked: isLocked,
  displayOrder: displayOrder,
  isQueue: isQueue,
);

Future<List<String>> resolveContent({
  required String collectionId,
  required BigInt maxDepth,
}) => RustLib.instance.api.crateApiCollectionApiResolveContent(
  collectionId: collectionId,
  maxDepth: maxDepth,
);

Future<bool> wouldCreateCircularReference({
  required String parentId,
  required String targetId,
}) => RustLib.instance.api.crateApiCollectionApiWouldCreateCircularReference(
  parentId: parentId,
  targetId: targetId,
);

/// FRB-transparent collection representation.
/// All fields are simple types so FRB generates a non-opaque Dart class.
class DartCollection {
  const DartCollection({
    required this.id,
    required this.name,
    required this.collectionType,
    required this.isLocked,
    required this.displayOrder,
    required this.items,
    required this.currentIndex,
    required this.playbackPositionMs,
    required this.wasPlaying,
    required this.removeAfterPlay,
    required this.isQueue,
    required this.createdAt,
    required this.updatedAt,
    this.parentId,
    required this.aliasNames,
    required this.includeChildren,
    required this.isGroup,
  });
  final String id;
  final String name;
  final String collectionType;
  final bool isLocked;
  final int displayOrder;
  final List<DartCollectionItem> items;
  final int currentIndex;
  final PlatformInt64 playbackPositionMs;
  final bool wasPlaying;
  final bool removeAfterPlay;
  final bool isQueue;
  final String createdAt;
  final String updatedAt;
  final String? parentId;
  final List<String> aliasNames;
  final bool includeChildren;
  final bool isGroup;

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      collectionType.hashCode ^
      isLocked.hashCode ^
      displayOrder.hashCode ^
      items.hashCode ^
      currentIndex.hashCode ^
      playbackPositionMs.hashCode ^
      wasPlaying.hashCode ^
      removeAfterPlay.hashCode ^
      isQueue.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      parentId.hashCode ^
      aliasNames.hashCode ^
      includeChildren.hashCode ^
      isGroup.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DartCollection &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          collectionType == other.collectionType &&
          isLocked == other.isLocked &&
          displayOrder == other.displayOrder &&
          items == other.items &&
          currentIndex == other.currentIndex &&
          playbackPositionMs == other.playbackPositionMs &&
          wasPlaying == other.wasPlaying &&
          removeAfterPlay == other.removeAfterPlay &&
          isQueue == other.isQueue &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          parentId == other.parentId &&
          aliasNames == other.aliasNames &&
          includeChildren == other.includeChildren &&
          isGroup == other.isGroup;
}

/// FRB-transparent collection item representation.
class DartCollectionItem {
  const DartCollectionItem({
    required this.id,
    required this.itemType,
    required this.targetId,
    required this.order,
    required this.inheritLock,
  });
  final String id;
  final String itemType;
  final String targetId;
  final int order;
  final bool inheritLock;

  @override
  int get hashCode =>
      id.hashCode ^
      itemType.hashCode ^
      targetId.hashCode ^
      order.hashCode ^
      inheritLock.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DartCollectionItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          itemType == other.itemType &&
          targetId == other.targetId &&
          order == other.order &&
          inheritLock == other.inheritLock;
}
