// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

// These functions are ignored because they are not marked as `pub`: `db_slot`, `lock_db`

/// Initialize the SQLite database at `db_path`.
///
/// Runs migrations and ensures built-in tags exist.
/// Must be called once before any other tag/search operations.
Future<void> initDatabase({required String dbPath}) =>
    RustLib.instance.api.crateApiDatabaseApiInitDatabase(dbPath: dbPath);

/// Close the database connection.
///
/// After calling this, no further tag/search operations are possible
/// until `init_database()` is called again.
Future<void> closeDatabase() =>
    RustLib.instance.api.crateApiDatabaseApiCloseDatabase();
