// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

Future<List<String>> filterSongUnits({
  required QueryExpression expr,
  required List<SongUnitView> units,
}) => RustLib.instance.api.crateApiEvaluatorApiFilterSongUnits(
  expr: expr,
  units: units,
);

/// High-level search: parse query, fetch song units + tags from DB, evaluate,
/// return matching IDs.
///
/// The API is intentionally simple — just query text in, matching IDs out.
/// The Rust side fetches everything from the database itself.
///
/// Metadata fields (name, artist, album) are injected as synthetic named tags
/// so the evaluator treats them identically to real tags. This aligns with the
/// design philosophy that metadata IS built-in tags — they're just convenient
/// defaults that are always present.
Future<List<String>> searchSongUnits({
  required String queryText,
  required bool nameAutoSearch,
}) => RustLib.instance.api.crateApiEvaluatorApiSearchSongUnits(
  queryText: queryText,
  nameAutoSearch: nameAutoSearch,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<QueryExpression>>
abstract class QueryExpression implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SongUnitView>>
abstract class SongUnitView implements RustOpaqueInterface {}
