// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Extract metadata + embedded artwork from an audio file using lofty.
/// Returns `None` if the file cannot be read or is not a supported format.
Future<LoftyMetadata?> extractMediaMetadata({required String filePath}) =>
    RustLib.instance.api.crateApiMediaApiExtractMediaMetadata(
      filePath: filePath,
    );

/// Metadata extracted from an audio file via lofty.
class LoftyMetadata {
  const LoftyMetadata({
    this.title,
    this.artist,
    this.album,
    this.year,
    required this.durationMs,
    required this.artwork,
  });
  final String? title;
  final String? artist;
  final String? album;
  final int? year;
  final BigInt durationMs;

  /// Embedded artwork bytes (JPEG/PNG). Empty if none found.
  final Uint8List artwork;

  @override
  int get hashCode =>
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      year.hashCode ^
      durationMs.hashCode ^
      artwork.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LoftyMetadata &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          year == other.year &&
          durationMs == other.durationMs &&
          artwork == other.artwork;
}
