// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';
import 'evaluator_api.dart';

Future<QueryExpression> parseQuery({
  required String input,
  required bool nameAutoSearch,
}) => RustLib.instance.api.crateApiParserApiParseQuery(
  input: input,
  nameAutoSearch: nameAutoSearch,
);

Future<String> serializeQuery({required QueryExpression expr}) =>
    RustLib.instance.api.crateApiParserApiSerializeQuery(expr: expr);

Future<List<QueryChip>> parseToChips({
  required String input,
  required bool nameAutoSearch,
}) => RustLib.instance.api.crateApiParserApiParseToChips(
  input: input,
  nameAutoSearch: nameAutoSearch,
);

/// Parse a query string and return chips as Dart-friendly structs.
Future<List<DartQueryChip>> parseToDartChips({
  required String input,
  required bool nameAutoSearch,
}) => RustLib.instance.api.crateApiParserApiParseToDartChips(
  input: input,
  nameAutoSearch: nameAutoSearch,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<QueryChip>>
abstract class QueryChip implements RustOpaqueInterface {}

/// A Dart-friendly chip representation with all fields as simple types.
/// FRB can serialize this directly (no opaque wrapper needed).
class DartQueryChip {
  const DartQueryChip({
    required this.chipType,
    required this.text,
    required this.start,
    required this.end,
  });

  /// Chip type as a string: "named_tag", "nameless_tag", "bare_keyword", "range", "negation", "or_operator"
  final String chipType;

  /// The display text for this chip
  final String text;

  /// Byte offset of the chip's start in the original query string
  final BigInt start;

  /// Byte offset of the chip's end in the original query string
  final BigInt end;

  @override
  int get hashCode =>
      chipType.hashCode ^ text.hashCode ^ start.hashCode ^ end.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DartQueryChip &&
          runtimeType == other.runtimeType &&
          chipType == other.chipType &&
          text == other.text &&
          start == other.start &&
          end == other.end;
}
