// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

// These functions are ignored because they are not marked as `pub`: `to_domain`, `to_ffi`

Future<void> createSongUnit({
  required String id,
  required String metadataJson,
  required String sourcesJson,
  required String preferencesJson,
  required List<String> tagIds,
  String? libraryLocationId,
  required bool isTemporary,
  PlatformInt64? discoveredAt,
  String? originalFilePath,
}) => RustLib.instance.api.crateApiSongUnitApiCreateSongUnit(
  id: id,
  metadataJson: metadataJson,
  sourcesJson: sourcesJson,
  preferencesJson: preferencesJson,
  tagIds: tagIds,
  libraryLocationId: libraryLocationId,
  isTemporary: isTemporary,
  discoveredAt: discoveredAt,
  originalFilePath: originalFilePath,
);

Future<FfiSongUnit?> getSongUnit({required String id}) =>
    RustLib.instance.api.crateApiSongUnitApiGetSongUnit(id: id);

Future<void> updateSongUnit({
  required String id,
  required String metadataJson,
  required String sourcesJson,
  required String preferencesJson,
  required List<String> tagIds,
  String? libraryLocationId,
  required bool isTemporary,
  PlatformInt64? discoveredAt,
  String? originalFilePath,
}) => RustLib.instance.api.crateApiSongUnitApiUpdateSongUnit(
  id: id,
  metadataJson: metadataJson,
  sourcesJson: sourcesJson,
  preferencesJson: preferencesJson,
  tagIds: tagIds,
  libraryLocationId: libraryLocationId,
  isTemporary: isTemporary,
  discoveredAt: discoveredAt,
  originalFilePath: originalFilePath,
);

Future<void> deleteSongUnit({required String id}) =>
    RustLib.instance.api.crateApiSongUnitApiDeleteSongUnit(id: id);

Future<List<FfiSongUnit>> getSongUnitsPaginated({
  required BigInt offset,
  required BigInt limit,
}) => RustLib.instance.api.crateApiSongUnitApiGetSongUnitsPaginated(
  offset: offset,
  limit: limit,
);

Future<List<FfiSongUnit>> getAllSongUnits() =>
    RustLib.instance.api.crateApiSongUnitApiGetAllSongUnits();

Future<List<FfiSongUnit>> getSongUnitsByLibraryLocation({
  required String locationId,
}) => RustLib.instance.api.crateApiSongUnitApiGetSongUnitsByLibraryLocation(
  locationId: locationId,
);

Future<List<FfiSongUnit>> getSongUnitsByHash({required String hash}) =>
    RustLib.instance.api.crateApiSongUnitApiGetSongUnitsByHash(hash: hash);

Future<List<FfiSongUnit>> getTemporarySongUnits() =>
    RustLib.instance.api.crateApiSongUnitApiGetTemporarySongUnits();

Future<bool> hasTemporarySongUnitForPath({required String filePath}) => RustLib
    .instance
    .api
    .crateApiSongUnitApiHasTemporarySongUnitForPath(filePath: filePath);

Future<BigInt> deleteAllTemporarySongUnits() =>
    RustLib.instance.api.crateApiSongUnitApiDeleteAllTemporarySongUnits();

Future<BigInt> deleteTemporarySongUnitByPath({required String filePath}) =>
    RustLib.instance.api.crateApiSongUnitApiDeleteTemporarySongUnitByPath(
      filePath: filePath,
    );

Future<BigInt> getSongUnitCount() =>
    RustLib.instance.api.crateApiSongUnitApiGetSongUnitCount();

Future<String> calculateSongUnitHash({
  required String metadataJson,
  required String sourcesJson,
}) => RustLib.instance.api.crateApiSongUnitApiCalculateSongUnitHash(
  metadataJson: metadataJson,
  sourcesJson: sourcesJson,
);

/// Flat struct for FFI transport — avoids nested enums that FRB struggles with.
/// The Dart side reconstructs the full SongUnit from these JSON strings.
class FfiSongUnit {
  const FfiSongUnit({
    required this.id,
    required this.metadataJson,
    required this.sourcesJson,
    required this.preferencesJson,
    required this.tagIds,
    this.libraryLocationId,
    required this.isTemporary,
    this.discoveredAt,
    this.originalFilePath,
  });
  final String id;
  final String metadataJson;
  final String sourcesJson;
  final String preferencesJson;
  final List<String> tagIds;
  final String? libraryLocationId;
  final bool isTemporary;
  final PlatformInt64? discoveredAt;
  final String? originalFilePath;

  @override
  int get hashCode =>
      id.hashCode ^
      metadataJson.hashCode ^
      sourcesJson.hashCode ^
      preferencesJson.hashCode ^
      tagIds.hashCode ^
      libraryLocationId.hashCode ^
      isTemporary.hashCode ^
      discoveredAt.hashCode ^
      originalFilePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiSongUnit &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          metadataJson == other.metadataJson &&
          sourcesJson == other.sourcesJson &&
          preferencesJson == other.preferencesJson &&
          tagIds == other.tagIds &&
          libraryLocationId == other.libraryLocationId &&
          isTemporary == other.isTemporary &&
          discoveredAt == other.discoveredAt &&
          originalFilePath == other.originalFilePath;
}
