// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

Future<List<Suggestion>> getSuggestions({
  required String fragment,
  required int maxResults,
}) => RustLib.instance.api.crateApiSuggestionApiGetSuggestions(
  fragment: fragment,
  maxResults: maxResults,
);

/// Get suggestions and return them as Dart-friendly structs.
Future<List<DartSuggestion>> getDartSuggestions({
  required String fragment,
  required int maxResults,
}) => RustLib.instance.api.crateApiSuggestionApiGetDartSuggestions(
  fragment: fragment,
  maxResults: maxResults,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Suggestion>>
abstract class Suggestion implements RustOpaqueInterface {}

/// A Dart-friendly suggestion representation with all fields as simple types.
/// FRB can serialize this directly (no opaque wrapper needed).
class DartSuggestion {
  const DartSuggestion({
    required this.displayText,
    required this.insertText,
    required this.suggestionType,
  });

  /// Text shown to the user in the dropdown.
  final String displayText;

  /// Text inserted into the query when the user selects this suggestion.
  final String insertText;

  /// Suggestion type as a string: "named_tag_key", "named_tag_value", "nameless_tag", "hierarchical_tag"
  final String suggestionType;

  @override
  int get hashCode =>
      displayText.hashCode ^ insertText.hashCode ^ suggestionType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DartSuggestion &&
          runtimeType == other.runtimeType &&
          displayText == other.displayText &&
          insertText == other.insertText &&
          suggestionType == other.suggestionType;
}
