// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

/// Convert a Rust Tag to a DartTag for FFI transport.
Future<DartTag> toDartTag({required Tag tag}) =>
    RustLib.instance.api.crateApiTagApiToDartTag(tag: tag);

/// Convert a DartTag back to a Rust Tag (used by update_tag).
Future<Tag> fromDartTag({required DartTag dt}) =>
    RustLib.instance.api.crateApiTagApiFromDartTag(dt: dt);

Future<DartTag> createTag({
  String? key,
  required String value,
  String? parentId,
}) => RustLib.instance.api.crateApiTagApiCreateTag(
  key: key,
  value: value,
  parentId: parentId,
);

Future<void> deleteTag({required String id}) =>
    RustLib.instance.api.crateApiTagApiDeleteTag(id: id);

Future<DartTag> updateTag({required DartTag tag}) =>
    RustLib.instance.api.crateApiTagApiUpdateTag(tag: tag);

Future<DartTag?> getTag({required String id}) =>
    RustLib.instance.api.crateApiTagApiGetTag(id: id);

Future<List<DartTag>> getAllTags() =>
    RustLib.instance.api.crateApiTagApiGetAllTags();

Future<List<DartTag>> getChildren({required String parentId}) =>
    RustLib.instance.api.crateApiTagApiGetChildren(parentId: parentId);

Future<List<DartTag>> getDescendants({required String tagId}) =>
    RustLib.instance.api.crateApiTagApiGetDescendants(tagId: tagId);

Future<void> addAlias({required String tagId, required String alias}) =>
    RustLib.instance.api.crateApiTagApiAddAlias(tagId: tagId, alias: alias);

Future<void> removeAlias({required String alias}) =>
    RustLib.instance.api.crateApiTagApiRemoveAlias(alias: alias);

Future<DartTag?> resolveTag({required String nameOrAlias}) =>
    RustLib.instance.api.crateApiTagApiResolveTag(nameOrAlias: nameOrAlias);

Future<String> getTagPath({required String tagId}) =>
    RustLib.instance.api.crateApiTagApiGetTagPath(tagId: tagId);

Future<List<DartTag>> getTagsByType({required String tagType}) =>
    RustLib.instance.api.crateApiTagApiGetTagsByType(tagType: tagType);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Tag>>
abstract class Tag implements RustOpaqueInterface {}

/// FRB-transparent tag representation.
/// All fields are simple types so FRB generates a non-opaque Dart class.
class DartTag {
  const DartTag({
    required this.id,
    required this.name,
    this.key,
    required this.tagType,
    this.parentId,
    required this.aliasNames,
    required this.includeChildren,
    required this.isGroup,
    required this.isLocked,
    required this.displayOrder,
    required this.hasCollectionMetadata,
  });
  final String id;
  final String name;
  final String? key;
  final String tagType;
  final String? parentId;
  final List<String> aliasNames;
  final bool includeChildren;
  final bool isGroup;
  final bool isLocked;
  final int displayOrder;
  final bool hasCollectionMetadata;

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      key.hashCode ^
      tagType.hashCode ^
      parentId.hashCode ^
      aliasNames.hashCode ^
      includeChildren.hashCode ^
      isGroup.hashCode ^
      isLocked.hashCode ^
      displayOrder.hashCode ^
      hasCollectionMetadata.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DartTag &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          key == other.key &&
          tagType == other.tagType &&
          parentId == other.parentId &&
          aliasNames == other.aliasNames &&
          includeChildren == other.includeChildren &&
          isGroup == other.isGroup &&
          isLocked == other.isLocked &&
          displayOrder == other.displayOrder &&
          hasCollectionMetadata == other.hasCollectionMetadata;
}
