// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

// These functions are ignored because they are not marked as `pub`: `domain_to_ffi`, `ffi_to_domain`

Future<Tag> createTag({String? key, required String value, String? parentId}) =>
    RustLib.instance.api.crateApiTagApiCreateTag(
      key: key,
      value: value,
      parentId: parentId,
    );

Future<void> deleteTag({required String id}) =>
    RustLib.instance.api.crateApiTagApiDeleteTag(id: id);

Future<Tag> updateTag({required Tag tag}) =>
    RustLib.instance.api.crateApiTagApiUpdateTag(tag: tag);

Future<Tag?> getTag({required String id}) =>
    RustLib.instance.api.crateApiTagApiGetTag(id: id);

Future<List<Tag>> getAllTags() =>
    RustLib.instance.api.crateApiTagApiGetAllTags();

Future<List<Tag>> getChildren({required String parentId}) =>
    RustLib.instance.api.crateApiTagApiGetChildren(parentId: parentId);

Future<List<Tag>> getDescendants({required String tagId}) =>
    RustLib.instance.api.crateApiTagApiGetDescendants(tagId: tagId);

Future<void> addAlias({required String tagId, required String alias}) =>
    RustLib.instance.api.crateApiTagApiAddAlias(tagId: tagId, alias: alias);

Future<void> removeAlias({required String alias}) =>
    RustLib.instance.api.crateApiTagApiRemoveAlias(alias: alias);

Future<Tag?> resolveTag({required String nameOrAlias}) =>
    RustLib.instance.api.crateApiTagApiResolveTag(nameOrAlias: nameOrAlias);

Future<String> getTagPath({required String tagId}) =>
    RustLib.instance.api.crateApiTagApiGetTagPath(tagId: tagId);

Future<List<Tag>> getTagsByType({required String tagType}) =>
    RustLib.instance.api.crateApiTagApiGetTagsByType(tagType: tagType);

/// A tag — the unified model for tags, playlists, queues, and groups.
/// When `metadata` is `Some`, this tag contains songs.
class Tag {
  const Tag({
    required this.id,
    required this.name,
    this.key,
    required this.tagType,
    this.parentId,
    required this.aliasNames,
    required this.includeChildren,
    required this.isGroup,
    required this.isLocked,
    required this.displayOrder,
    this.metadata,
  });
  final String id;
  final String name;
  final String? key;
  final TagType tagType;
  final String? parentId;
  final List<String> aliasNames;
  final bool includeChildren;
  final bool isGroup;
  final bool isLocked;
  final int displayOrder;
  final TagMetadata? metadata;

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      key.hashCode ^
      tagType.hashCode ^
      parentId.hashCode ^
      aliasNames.hashCode ^
      includeChildren.hashCode ^
      isGroup.hashCode ^
      isLocked.hashCode ^
      displayOrder.hashCode ^
      metadata.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Tag &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          key == other.key &&
          tagType == other.tagType &&
          parentId == other.parentId &&
          aliasNames == other.aliasNames &&
          includeChildren == other.includeChildren &&
          isGroup == other.isGroup &&
          isLocked == other.isLocked &&
          displayOrder == other.displayOrder &&
          metadata == other.metadata;
}

/// A single item entry in a tag's metadata.
class TagItem {
  const TagItem({
    required this.id,
    required this.itemType,
    required this.targetId,
    required this.order,
    required this.inheritLock,
  });
  final String id;
  final TagItemType itemType;
  final String targetId;
  final int order;
  final bool inheritLock;

  @override
  int get hashCode =>
      id.hashCode ^
      itemType.hashCode ^
      targetId.hashCode ^
      order.hashCode ^
      inheritLock.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TagItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          itemType == other.itemType &&
          targetId == other.targetId &&
          order == other.order &&
          inheritLock == other.inheritLock;
}

/// Item type within a tag's metadata.
enum TagItemType { songUnit, tagReference }

/// Metadata for tags that contain songs (playlists/queues/groups).
class TagMetadata {
  const TagMetadata({
    required this.isLocked,
    required this.displayOrder,
    required this.items,
    required this.currentIndex,
    required this.playbackPositionMs,
    required this.wasPlaying,
    required this.removeAfterPlay,
    required this.isQueue,
    required this.createdAt,
    required this.updatedAt,
  });
  final bool isLocked;
  final int displayOrder;
  final List<TagItem> items;
  final int currentIndex;
  final PlatformInt64 playbackPositionMs;
  final bool wasPlaying;
  final bool removeAfterPlay;
  final bool isQueue;
  final String createdAt;
  final String updatedAt;

  @override
  int get hashCode =>
      isLocked.hashCode ^
      displayOrder.hashCode ^
      items.hashCode ^
      currentIndex.hashCode ^
      playbackPositionMs.hashCode ^
      wasPlaying.hashCode ^
      removeAfterPlay.hashCode ^
      isQueue.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TagMetadata &&
          runtimeType == other.runtimeType &&
          isLocked == other.isLocked &&
          displayOrder == other.displayOrder &&
          items == other.items &&
          currentIndex == other.currentIndex &&
          playbackPositionMs == other.playbackPositionMs &&
          wasPlaying == other.wasPlaying &&
          removeAfterPlay == other.removeAfterPlay &&
          isQueue == other.isQueue &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

/// Tag type classification.
enum TagType { builtIn, user, automatic }
