// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

// These functions are ignored because they are not marked as `pub`: `make_cache`

/// Cache bytes and return the 64-char hex content hash.
Future<String> thumbnailCacheFromBytes({
  required String cacheDir,
  required List<int> bytes,
}) => RustLib.instance.api.crateApiThumbnailCacheApiThumbnailCacheFromBytes(
  cacheDir: cacheDir,
  bytes: bytes,
);

/// Return absolute path string if the entry exists, None otherwise.
Future<String?> thumbnailCacheGet({
  required String cacheDir,
  required String contentHash,
}) => RustLib.instance.api.crateApiThumbnailCacheApiThumbnailCacheGet(
  cacheDir: cacheDir,
  contentHash: contentHash,
);

/// Delete orphan .jpg files. Returns count deleted.
Future<int> thumbnailCachePurgeOrphans({
  required String cacheDir,
  required List<String> referencedHashes,
}) => RustLib.instance.api.crateApiThumbnailCacheApiThumbnailCachePurgeOrphans(
  cacheDir: cacheDir,
  referencedHashes: referencedHashes,
);

/// Return hashes from the input set that have no corresponding file.
Future<List<String>> thumbnailCacheFindMissing({
  required String cacheDir,
  required List<String> referencedHashes,
}) => RustLib.instance.api.crateApiThumbnailCacheApiThumbnailCacheFindMissing(
  cacheDir: cacheDir,
  referencedHashes: referencedHashes,
);

/// Return aggregate cache statistics.
Future<RustCacheStats> thumbnailCacheGetStats({
  required String cacheDir,
  required List<String> referencedHashes,
}) => RustLib.instance.api.crateApiThumbnailCacheApiThumbnailCacheGetStats(
  cacheDir: cacheDir,
  referencedHashes: referencedHashes,
);

/// FRB-compatible cache stats struct.
class RustCacheStats {
  const RustCacheStats({
    required this.totalEntries,
    required this.totalBytes,
    required this.orphanCount,
  });
  final int totalEntries;
  final BigInt totalBytes;
  final int orphanCount;

  @override
  int get hashCode =>
      totalEntries.hashCode ^ totalBytes.hashCode ^ orphanCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustCacheStats &&
          runtimeType == other.runtimeType &&
          totalEntries == other.totalEntries &&
          totalBytes == other.totalBytes &&
          orphanCount == other.orphanCount;
}
